// Generated by CoffeeScript 2.7.0
var Audio, Game, Settings, UI, a, animate, answer, check, checkAnswer, g, generateTones, getFrequencySpan, getOscillator, play, rand, s, setup, setupAudio, setupClicks, setupKeyBindings, setupUI, startRound, ui;

Settings = (function() {
  class Settings {};

  // Animations
  Settings.prototype.ANIMATION_TIME = 128;

  Settings.prototype.LOWEST_FREQUENCY = 110;

  Settings.prototype.HIGHEST_FREQUENCY = 880;

  Settings.prototype.PLAYING_TIME = 1024;

  Settings.prototype.GAIN = 0.1;

  return Settings;

}).call(this);

Game = (function() {
  class Game {};

  Game.prototype.firstFrequency = 0;

  Game.prototype.secondFrequency = 0;

  Game.prototype.currentPlayer = null;

  return Game;

}).call(this);

Audio = (function() {
  class Audio {};

  Audio.prototype.context = null;

  Audio.prototype.oscillator = null;

  Audio.prototype.gain = null;

  return Audio;

}).call(this);

UI = (function() {
  class UI {};

  // Repeat
  UI.prototype.$first = null;

  UI.prototype.$second = null;

  // Choices
  UI.prototype.$lower = null;

  UI.prototype.$equal = null;

  UI.prototype.$higher = null;

  return UI;

}).call(this);

s = new Settings();

g = new Game();

a = new Audio();

ui = new UI();

getFrequencySpan = function(frequency) {
  var base, high, low;
  low = s.LOWEST_FREQUENCY;
  base = low;
  while (true) {
    if (base <= frequency && frequency < 2 * base) {
      break;
    } else {
      base *= 2;
    }
  }
  high = base;
  return [low, high];
};

rand = function(minimum, maximum) {
  var random;
  random = minimum + Math.random() * (maximum - minimum + 1);
  return Math.floor(random);
};

generateTones = function() {
  var first, frequencySpan, high, low, second;
  first = rand(s.LOWEST_FREQUENCY, s.HIGHEST_FREQUENCY);
  frequencySpan = getFrequencySpan(first);
  [low, high] = frequencySpan;
  second = rand(low, high);
  g.firstFrequency = first;
  return g.secondFrequency = second;
};

getOscillator = function(frequency) {
  var gain, oscillator;
  oscillator = a.context.createOscillator();
  gain = a.context.createGain();
  gain.gain.value = s.GAIN;
  oscillator.connect(gain);
  oscillator.type = 'sine';
  oscillator.frequency.setValueAtTime(frequency, a.context.currentTime);
  oscillator.connect(a.context.destination);
  return oscillator;
};

checkAnswer = function(answer) {
  var $advices, $body, success;
  switch (answer) {
    case 'lower':
      success = g.firstFrequency > g.secondFrequency;
      break;
    case 'equal':
      success = g.firstFrequency === g.secondFrequency;
      break;
    case 'higher':
      success = g.firstFrequency < g.secondFrequency;
  }
  $body = $('body');
  $advices = $('.advice');
  if (success) {
    $body.removeClass('body-inverted');
    $advices.removeClass('advice-inverted');
  } else {
    $body.addClass('body-inverted');
    $advices.addClass('advice-inverted');
  }
  a.oscillator.stop();
  return generateTones();
};

animate = function(self) {
  var $this;
  $this = $(self);
  return $this.animate({
    'width': '-=16px',
    'height': '-=16px',
    'margin-top': '+=8px',
    'margin-left': '+=8px'
  }, s.ANIMATION_TIME, 'swing', function() {
    return $this.animate({
      'width': '+=16px',
      'height': '+=16px',
      'margin-top': '-=8px',
      'margin-left': '-=8px'
    }, s.ANIMATION_TIME);
  });
};

play = function(frequency, name) {
  var ref;
  if (g.currentPlayer === name) {
    a.oscillator.stop();
  } else {
    if ((ref = a.oscillator) != null) {
      ref.stop();
    }
    a.oscillator = getOscillator(frequency);
    a.oscillator.start();
  }
  return g.currentPlayer = name;
};

check = function(self, frequency, name) {
  if (!g.isRoundStarting) {
    animate(self);
    return play(frequency, name);
  }
};

answer = function(self, name) {
  if (!g.isRoundStarting) {
    animate(self);
    checkAnswer(name);
    return startRound();
  }
};

setupUI = function() {
  ui.$first = $('#first');
  ui.$second = $('#second');
  ui.$lower = $('#lower');
  ui.$equal = $('#equal');
  return ui.$higher = $('#higher');
};

setupKeyBindings = function() {
  Mousetrap.bind('left', function() {
    return ui.$first.click();
  });
  Mousetrap.bind('right', function() {
    return ui.$second.click();
  });
  Mousetrap.bind('down', function() {
    return ui.$lower.click();
  });
  Mousetrap.bind('space', function() {
    return ui.$equal.click();
  });
  return Mousetrap.bind('up', function() {
    return ui.$higher.click();
  });
};

setupClicks = function() {
  ui.$first.click(function() {
    return check(this, g.firstFrequency, 'first');
  });
  ui.$second.click(function() {
    return check(this, g.secondFrequency, 'second');
  });
  ui.$lower.click(function() {
    return answer(this, 'lower');
  });
  ui.$equal.click(function() {
    return answer(this, 'equal');
  });
  return ui.$higher.click(function() {
    return answer(this, 'higher');
  });
};

setupAudio = function() {
  var audioContext;
  audioContext = window.AudioContext || window.webkitAudioContext || false;
  if (audioContext) {
    return a.context = new audioContext();
  } else {
    return console.error('Nor window.AudioContext, nor window.webkitAudioContext is supported. Cannot continue.');
  }
};

startRound = function() {
  generateTones();
  play(g.firstFrequency, 'first');
  return setTimeout(function() {
    play(g.secondFrequency, 'second');
    return setTimeout(function() {
      return a.oscillator.stop();
    }, s.PLAYING_TIME);
  }, s.PLAYING_TIME);
};

setup = function() {
  setupUI();
  setupKeyBindings();
  setupClicks();
  return setupAudio();
};

$(function() {
  setup();
  return startRound();
});
